server:
  port: 8081

spring:
  application:
    name: gestaoEmpresarial
  # Configuração do banco de dados H2 em memória
  h2:
    console:
      enabled: true
      path: /h2-console
  # Configuração do DataSource para H2
  datasource:
    url: jdbc:h2:mem:gestaoEmpresarial;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # Configuração do JPA e Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true